_wandb:
    value:
        cli_version: 0.23.1
        code_path: code/projet.ipynb
        e:
            2cyqivzjzjvq6ododqi5xh3p21xlzp7n:
                codePath: projet.ipynb
                codePathLocal: projet.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1002443894784"
                        used: "757351579648"
                email: arthur.collignon@cpe.fr
                executable: C:\Users\arthu\Work\CPE\S9\ReinforcementLearning\Projet\.venv\Scripts\python.exe
                git:
                    commit: b046000f45f19b1bbb79ae19347e2f6c9d59c6ff
                    remote: https://github.com/Arthur-Collignon/RL_Project_Money.git
                host: Pac_Computer
                memory:
                    total: "16848695296"
                os: Windows-11-10.0.26200-SP0
                program: projet.ipynb
                python: CPython 3.13.7
                root: C:\Users\arthu\Work\CPE\S9\ReinforcementLearning\Projet
                startedAt: "2025-12-22T09:48:36.971819Z"
                writerId: 2cyqivzjzjvq6ododqi5xh3p21xlzp7n
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 34
                - 35
            "4": 3.13.7
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 128
ent_coef:
    value: 0.01
learning_rate:
    value: 0.0003
n_steps:
    value: 2048
policy_type:
    value: MlpLstmPolicy
positions:
    value:
        - 0
        - 0.5
        - 1
project_name:
    value: RL-Trading-Project
run_name:
    value: RecurrentPPO_Optimized
total_timesteps:
    value: 500000
window_size:
    value: 20
