_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[-1.5834285e-02  1.3780586e-01 -1.0219604e+02  3.9383072e-01
           3.9383072e-01]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001BBC32CEF90>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 200000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.23.1
        code_path: source-RL-Trading-Project-projet.ipynb
        e:
            lk5ajr6u9ysren9nxu7btl6dp36ix1ts:
                codePath: projet.ipynb
                codePathLocal: projet.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1002443894784"
                        used: "757725044736"
                email: arthur.collignon@cpe.fr
                executable: C:\Users\arthu\Work\CPE\S9\ReinforcementLearning\Projet\.venv\Scripts\python.exe
                git:
                    commit: b046000f45f19b1bbb79ae19347e2f6c9d59c6ff
                    remote: https://github.com/Arthur-Collignon/RL_Project_Money.git
                host: Pac_Computer
                memory:
                    total: "16848695296"
                os: Windows-11-10.0.26200-SP0
                program: projet.ipynb
                python: CPython 3.13.7
                root: C:\Users\arthu\Work\CPE\S9\ReinforcementLearning\Projet
                startedAt: "2025-12-22T09:23:05.700704Z"
                writerId: lk5ajr6u9ysren9nxu7btl6dp36ix1ts
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 3
                - 16
                - 22
                - 35
            "4": 3.13.7
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Discrete(8)
algo:
    value: PPO
batch_size:
    value: 128
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.02
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001BBBBF34440>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (5,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=5, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=5, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=8, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
policy_type:
    value: MlpPolicy
positions:
    value:
        - -0.5
        - 0
        - 0.25
        - 0.5
        - 0.75
        - 1
        - 1.25
        - 1.5
project_name:
    value: RL-Trading-Project
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001BBBBF34830>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1766395395368079400
target_kl:
    value: None
tensorboard_log:
    value: runs/n6etkjbb
total_timesteps:
    value: 200000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
